---
title: "Test"
author: "Ziwei Huang"
date:   "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    theme: united
    code_folding: hide
    toc: true
    toc_float: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setting
```{r}
rm(list = ls())
devtools::load_all(".")
library(hypeR.GEM)
library(reactable)
library(htmltools)
```

```{r}
data(EL_signature)
```


```{r}
hypeR_GEM_obj <- hypeR.GEM::signature2gene(signatures = EL_signature,
                                           species = "Human",
                                           ensemble_id = TRUE,
                                           reference_key = 'refmet_name',
                                           background = NULL)
```


```{r}
library(hypeR)
kegg <- hypeR::msigdb_gsets(species="Homo sapiens", category="C2", subcategory = "CP:KEGG", clean = TRUE)
print(kegg)
```


```{r}
max_fdr <- 0.01
hypeR_GEM_enrichments <- hypeR.GEM::enrichment(hypeR_GEM_obj,
                                         genesets = kegg$genesets,
                                         genesets_name = 'KEGG',
                                         method='unweighted',
                                         weights = 'one_minus_p_value',
                                         background=3068)
```



```{r}
hypeR_GEM_enrichment$EL_up$info
```

```{r}
#' Format a string using placeholders
#'
#' @param string A an unformatted string with placeholders
#' @param ... Variables to format placeholders with
#' @return A formatted string
#' 
#' @examples
#' \dontrun{
#' format_str("Format with {1} and {2}", "x", "y")
#' }
#'
#' @keywords internal
.format_str <- function(string, ...) {
    args <- list(...)
    for (i in 1:length(args)) {
        pattern <- paste("\\{", i, "}", sep="")
        replacement <- args[[i]]
        string <- gsub(pattern, replacement, string)
    }
    return(string)
}

rctbl <- function(hypeR_GEM_enrichment,
                  type=c("inner", "outer")){

    type <- match.arg(type)
    class.obj    <- .format_str("rctbl-{1}-obj", type)
    class.tbl    <- .format_str("rctbl-{1}-tbl", type)
    class.header <- .format_str("rctbl-{1}-header", type)

    df <- dplyr::select(hypeR_GEM_enrichment$data, c("label", "pval", "fdr", "geneset", "overlap", "weighted_overlap", "hits"))
    tbl <- reactable(df,
                     rownames=FALSE,
                     resizable=TRUE,
                     showPageSizeOptions=FALSE,
                     compact=TRUE, 
                     defaultColDef=colDef(headerClass=class.header),
                     columns=list(label   = colDef(name="Label", minWidth=300),
                                  pval    = colDef(name="P-Value"),
                                  fdr     = colDef(name="FDR"),
                                  geneset = colDef(name="Geneset Size"),
                                  overlap = colDef(name="Overlap"),
                                  weighted_overlap = colDef(name="Weighted overlap"),
                                  hits    = colDef(name="Hits")),
                     class=class.tbl)

    dat <- htmltools::div(class=class.obj, tbl)
    
     return(dat)
}
```


```{r}
outer_df = data.frame(signature = names(hypeR_GEM_enrichments),
                      size = sapply(hypeR_GEM_enrichments, function(x){x$info[["Signature_size"]]}),
                      gsets = sapply(hypeR_GEM_enrichment, function(x){x$info[["Gensets"]]}),
                      bg = sapply(hypeR_GEM_enrichment, function(x){x$info[["Background"]]}))

tbl <- reactable(outer_df, 
  showPageSizeOptions = FALSE,
  onClick = "expand",
  resizable = TRUE,
  rownames = FALSE,
  defaultColDef = colDef(headerClass="rctbl-outer-header"),
  columns = list(signature = colDef(name="Signature", minWidth=300),
                 size = colDef(name="Signature Size"),
                 gsets = colDef(name="Genesets"),
                 bg = colDef(name="Background")),
  details = function(index) {
    df <- rctbl(hypeR_GEM_enrichments[[index]], type="inner")
  },
  wrap = FALSE,
  class = "rctbl-outer-tbl",
  rowStyle = list(cursor="pointer")
  )
    

tbl
```






```{r}
fdr_cutoff <- 0.05
outer_df = data.frame(signature = names(hypeR_GEM_enrichment),
                      size = sapply(hypeR_GEM_enrichment, function(x){unique(x$data$signature)}),
                      enriched = sapply(hypeR_GEM_enrichment, function(x){x$data %>% filter(fdr < fdr_cutoff) %>% nrow(.)}),
                      gsets = sapply(hypeR_GEM_enrichment, function(x){x$genesets_name}),
                      bg = sapply(hypeR_GEM_enrichment, function(x){unique(x$data$signature)}



reactable(outer_df, 
  showPageSizeOptions = FALSE,
  onClick = "expand",
  resizable = TRUE,
  rownames = FALSE,
  details = function(index) {
  df <- hypeR_GEM_enrichment[[index]]$data
  htmltools::div(style = "padding: 1rem",
    reactable(df, outlined = TRUE)
  )
})                    
```

